baseURL = "https://jiahau3.github.io/"
languageCode = 'en-us'
title = "JH's Blog"
theme = 'PaperMod'

[params]
ShowBreadCrumbs = false
ShowReadingTime = true
    [params.assets]
    favicon = "/images/favicon.ico"

# home-info mode
[params.homeInfoParams]
    title = "Welcome to JH's Blog 🔭"
    content = 'Hi, I am Jia-Hau, passionate about discovering things through different scopes. Here to document things interested to me. Currently exploring things related to data science and machine learning.'

[[params.socialIcons]]
name = 'github'
url = "https://github.com/jiahau3"

[[params.socialIcons]]
name = 'youtube'
url = "https://www.youtube.com/channel/UCr86viYEHm-FFALl6wv7pHQ"

[[params.socialIcons]]
name = 'kaggle'
url = "https://www.kaggle.com/jiahauc"

[[params.socialIcons]]
name = 'twitter'
url = "https://twitter.com/JiahauChing"

[[params.socialIcons]]
name = 'paypal'
url = 'https://paypal.me/jiahauC?country.x=TW&locale.x=en_US'

[[params.socialIcons]]
name = 'upwork'
url = 'https://www.upwork.com/freelancers/~01c2a4024693ca5235?viewMode=1'

[[params.socialIcons]]
name = 'medium'
url = 'https://medium.com/@jiahau3'


[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/"
weight = 10

[[menu.main]]
identifier = "apps"
name = "Apps"
url = "/apps/"
weight = 20

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 30

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 40